4.1 namespace std
...
4.2 header file 's name and format
#include <string> //C++ class string
#include <cstring> //char * funtions from C

4.3error and exception process

class designed for aiming at language support
...
exception class designed for aiming at Logic error
...
exception class designed for aiming at runtime error
...

4.3.2 exception class member
member fun what()
the only member fun to get "Additional information other than the type(类型以外的附加信息)" is what() for all std exception,it returns byte string ended by null:
```C++
namespace std{
    class exception{
    public:
        virtual const char* what() const noexcept;
        ...
    };
}
```
C-string return by what() will be invalid if exception obj it belongs being destroyed or exception obj assigned with new value; 

Error Code and Error Condition
C++ std provides different types for error code and error condition:class std::error_code and class std::error_condition.you can use it to do:
```C++
if(ec == std::errc::invalid_argument){
    ...
}
if(ec == std::future_errc::no_state){
    ...
}
```
in order to process error code and condition ,class std::system_error and its derived std::ios_base::failure ,and  class std::_future_error,all provides nonvirtual mem fun code(),they returns std::error_code obj;
```C++
namespace std{
    class system_error: public runtimer_error{
    public:
        virtual const char * what() const noexcept;
        const error_code& code() const noexcept;
        ...
    };

    class future_....
}
```
and class error_code provides mem fun,u can get detail of error state;
```C++
namespace std{
    class error_code{
    public:
        const error_category& category() const noexcept
        int value() const noexcept;
        string message() const;
        error_condition default_error_condition() const noexcept;
        ...
    };
}
```
....
now show how to use generic fun to process different exception:
```C++
#include <exception>
#include <system_error>
#include <future>
#include <iostream>

template<typename T>
void processCodeException(const T& e){
    using namespace std;
    auto c = e.code;
    cerr << "- category:            "<< c.category().name() << endl;
    cerr << "- value:               "<< c.value() << endl;
    cerr << "- value:               "<< c.message() << endl;
    cerr << "- msg:                 "<< c.default_error_condtion().category().name() << endl;
    ...    
}
void processException(){
    using namespace std;
    try{

    }
    catch(){

    }
    .....
}

```
4.3.3 passing exception by Class exception_ptr
since C++11,stl provides a ability stroages exception in objecj whose type are exception_ptr,can process exception in other context(情境)；
```C++
#include <exception>
std::exception_ptr eptr;
void foo(){
    try{
        throw ...;
    }catch(...){
        eptr = std::current_exception();
    }
}
void bar(){
    if(eptr != nullptr){
        std::rethrow_exception(eptr);
    }
}
```

4.3.4 throw std exception

u can throw std exception in your own library or in procedure.all std exception has only one constructor to accept std::string and const char *,thos string will be what() return's string, which provides "logic error and runtime error" of what() api;
```C++
namespace std{
    class logic_error:public exception{
    public:
        explicit logic_error(const string& whatString);
        explicit logic_error(const char * whatString);
    };
}
```

std::system_error is special....
4.3.5 ...
----------------------------------------------------------------------------------------
4.4 callable obj
C++stl uses word callable obj in many palces,which means obj some fun can be called in some ways:
    a fun,accepts extra args as actual argument;
    
    a pointer to a mem fun,when u call it by obj,obj will be passed as first auctual argument(must be a reference or pointer),other arguments correspond to the mem fun arguments one by one;

    a fun obj(fun obj has operator()),with arguments passed as actual parameter;

    a lambda,strictly speaking it's a fun obj;

```C++
void func(int x ,int y);
auto l = [](int x ,int y){
    ...
};
class C{
    public:
        void operator()(int x,int y)const;
        void memfunc(int x,int y)const;
}
int main(){
    C c;
    std::shared_ptr<C>sp(new C);

    //bind() uses callable obj to bind arguments
    std::bind(func,77,33)();//  calls func(77,33)
    std::bind(l,77,33)();   //calls l
    std::bind(C(),7733)();//calls C::operator()(77,33)

    std::bind(&C::memfunc,c,77,33)();//calls c.memfunc(77,33)
    std::bind(&C::memfunc,sp,77,33)();//calls sp->memfunc(77,33)

    //async() uses callable obj to start(background) tasks:
    std::async(func,42,77);//calls func()
    std::async(l,42,77);    //calls l()
    std::async(c,42,77);//c.operator()(42,77)
    std::async(&C::memfunc,&c,42,77);//calls c.memfunc
    std::async(&C::memfunc,sp,42,77);//calls sp->memfunc();
}
```

4.5 concurrency and multithreading 

now has a memory model,makes sure two differnet obj independent of each other if u modify two different threads which are used;

induct(引入) a new key word thread_local,to define "thread-specific" value and obj;

general concurrency guarantee(一般性并发保证)
...
-------------------------------------------------------------------------------

4.6 allocator
...



